import type { PropsWithChildren } from "react";

import "./reset.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface IProps {}

function RootLayout(props: PropsWithChildren<IProps>) {
  const { children } = props;

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

export default RootLayout;
