name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn install --frozen-lockfile --no-audit
          yarn lint
          yarn lint:css
          yarn lint:ts
          yarn test:ci
