name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 20
      - run: |
          npm install --frozen-lockfile --no-audit --legacy-peer-deps
          npm run lint
          npm run lint:css
          npm run test:ci
