name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 20
      - run: |
          yarn install --frozen-lockfile --no-audit
          yarn lint
          yarn lint:css
          yarn test:ci
